name: Create preview environment

inputs:
  sa_key:
    description: "The service account key to use when authenticating with GCP"
    required: true
  name:
    description: "The name of the preview environment to deploy Gitpod to"
    required: false
  infrastructure_provider:
    description: "The infrastructure provider to use"
    required: true
  large_vm:
    description: "Whether to use a larger VM for the env"
    required: true
    default: false
  previewctl_hash:
    description: "The Leeway hash of the dev/preview/previewctl:docker package to be used when downloading previewclt"
    required: false
  recreate_vm:
    description: "Whether to recreate the VM"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Create preview environment
      shell: bash
      run: |
        gcloud auth activate-service-account --key-file "${PREVIEW_ENV_DEV_SA_KEY_PATH}"

        leeway run dev/preview/previewctl:download
        previewctl get-credentials --gcp-service-account "${PREVIEW_ENV_DEV_SA_KEY_PATH}"

        replace="module.preview_gce[0].google_compute_instance.default"
        if [[ "${INPUT_INFRASTRUCTURE_PROVIDER}" = "harvester " ]]; then
          replace="module.preview_harvester[0].harvester_virtualmachine.harvester"
        fi

        if [[ "${INPUT_RECREATE_VM:-x}" == "true" ]]; then
          export TF_CLI_ARGS_plan="-replace=${replace}"
        fi

        TF_VAR_preview_name="$(previewctl get-name --branch "${INPUT_NAME}")"
        export TF_VAR_preview_name
        export TF_VAR_infra_provider="${INPUT_INFRASTRUCTURE_PROVIDER}"
        export TF_VAR_with_large_vm="${INPUT_LARGE_VM}"
        export TF_INPUT=0
        export TF_IN_AUTOMATION=true
        leeway run dev/preview:create-preview
