name: "Deploy monitoring satellite"
description: "Deploys monitoring satellite to an existing preview environment"
inputs:
  name:
    description: "The name of the preview environment to deploy Gitpod to"
    required: false
  recreate_vm:
    description: "Whether to recreate the VM"
    required: false
    default: "false"
  sa_key:
    description: "GCP service account"
    required: true
  leeway_segment_key:
    description: "leeway analytics key"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
