name: Setup environment

inputs:
  sa_key:
    description: "GCP service account"
    required: true
  leeway_segment_key:
    description: "leeway analytics key"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: "${{ inputs.sa_key }}"
    - id: gcloud-auth
      name: gcloud auth activate-service-account
      shell: bash
      run: |
        gcloud auth activate-service-account --key-file ${{ steps.auth.outputs.credentials_file_path }}
    - id: env-vars
      name: configure env variables
      shell: bash
      run: |
        gcloud auth configure-docker eu.gcr.io --quiet

        {
            echo "LEEWAY_SEGMENT_KEY=${{ inputs.leeway_segment_key }}"
            echo "LEEWAY_WORKSPACE_ROOT=$GITHUB_WORKSPACE"
            echo "PREVIEW_ENV_DEV_SA_KEY_PATH=${{ steps.auth.outputs.credentials_file_path }}"
        }  >> "$GITHUB_ENV"
