name: Setup environment

inputs:
  sa_key:
    description: "GCP service account"
    required: true
  leeway_segment_key:
    description: "leeway analytics key"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: "${{ inputs.sa_key }}"
    - id: gcloud-auth
      name: gcloud auth activate-service-account
      shell: bash
      run: |
        gcloud auth activate-service-account --key-file ${{ steps.auth.outputs.credentials_file_path }}
        gcloud auth configure-docker eu.gcr.io --quiet
    - id: create-env-file
      name: Create .env file
      shell: bash
      run: |
        ENV_DIRECTORY=$(mktemp -d)

        cp "${{ steps.auth.outputs.credentials_file_path }}" "$ENV_DIRECTORY"

        echo "creating .env file"
        cat <<EOF >$ENV_DIRECTORY/.env
        LEEWAY_SEGMENT_KEY=${{ inputs.leeway_segment_key }}
        LEEWAY_WORKSPACE_ROOT=$GITHUB_WORKSPACE
        PREVIEW_ENV_DEV_SA_KEY_PATH=$ENV_DIRECTORY/$(basename ${{ steps.auth.outputs.credentials_file_path }})
        EOF

        echo "ENV_DIRECTORY=$ENV_DIRECTORY" >> "$GITHUB_ENV"
    - id: load-env-file
      name: Load .env file
      uses: xom9ikk/dotenv@v2
      with:
        path: ${{ env.ENV_DIRECTORY }}
        load-mode: strict
