packages:
  - name: lib
    type: go
    deps:
      - components/common-go:lib
      - components/usage-api/go:lib
    srcs:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
    config:
      packaging: library
      dontTest: false
