packages:
  - name: lib
    type: go
    deps:
     - components/gitpod-db/go:lib
    srcs:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
    config:
      packaging: library
      dontTest: false
