name: "Deploy Gitpod"
description: "Deploys Gitpod to an existing preview environment"
inputs:
  sa_key:
    description: "The service account key to use when authenticating with GCP"
    required: true
  name:
    description: "The name of the preview environment to deploy Gitpod to"
    required: false
  version:
    description: "The version of Gitpod to install"
    required: true
  with_dedicated_emu:
    description: "Dedicated Config"
    required: false
  analytics:
    description: "With analytics"
    required: false
  workspace_feature_flags:
    description: "Workspace feature flags"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
