packages:
  - name: raw-app
    type: go
    srcs:
      - go.mod
      - go.sum
      - "**/*.go"
      - "**/testdata/**/*"
      - "cmd/versions.yaml"
      - "pkg/components/**/*.tpl"
      - "pkg/components/**/*.crt"
      - "pkg/components/**/*.key"
      - "pkg/components/**/*.pem"
      - "pkg/components/**/*.sql"
      - "scripts/*.sh"
      - "third_party/**/*"
    deps:
      - components/blobserve:lib
      - components/common-go:lib
      - components/gitpod-db/go:lib
      - components/content-service-api/go:lib
      - components/content-service:lib
      - components/ee/agent-smith:lib
      - components/gitpod-protocol/go:lib
      - components/ide-metrics-api/go:lib
      - components/ide-service-api/go:lib
      - components/image-builder-api/go:lib
      - components/openvsx-proxy:lib
      - components/public-api/go:lib
      - components/registry-facade-api/go:lib
      - components/registry-facade:lib
      - components/ws-daemon-api/go:lib
      - components/ws-daemon:lib
      - components/ws-manager-api/go:lib
      - components/ws-proxy:lib
      - components/usage:lib
      - components/usage-api/go:lib
    env:
      - CGO_ENABLED=0
    prep:
      - ["sh", "-c", "ls -d third_party/charts/*/ | while read f; do echo \"cd $f && helm dep up && cd -\"; done | sh"]
    config:
      packaging: app
      buildCommand: ["go", "build", "-trimpath", "-ldflags", "-buildid= -w -s -X 'github.com/gitpod-io/gitpod/installer/cmd.Version=commit-${__git_commit}'"]
  - name: app
    type: generic
    srcs:
      - versions.yaml
    deps:
      - :raw-app
      - components:all-docker
    argdeps:
      - version
    config:
      commands:
        #- ["objcopy", "--add-section", "versionManifest=components--all-docker/versions.yaml", "install-installer--raw-app/installer", "installer"]

        # Use hard-coded versions.yaml (which is from release-2022.11.3) and replace version, commit and server version with new values.
        # That means we are re-using 2022.11.3 binaries except for server.
        - ["sh", "-c", 'yq w -i versions.yaml version "$(yq r components--all-docker/versions.yaml version)"']
        - ["sh", "-c", 'yq w -i versions.yaml commit "$(yq r components--all-docker/versions.yaml commit)"']
        - ["sh", "-c", 'yq w -i versions.yaml components.server.version "$(yq r components--all-docker/versions.yaml components.server.version)"']
        - ["objcopy", "--add-section", "versionManifest=versions.yaml", "install-installer--raw-app/installer", "installer"]
        # Remove the deps component folders now that we have copied over (and modified) the installer to reduce
        # the size of the build cache of this component.
        - ["rm", "-rf", "install-installer--raw-app", "components--all-docker"]
  - name: docker
    type: docker
    srcs:
      - "scripts/*.sh"
    deps:
      - :app
      - dev/gpctl:app
    argdeps:
      - imageRepoBase
    config:
      dockerfile: leeway.Dockerfile
      image:
        - ${imageRepoBase}/installer:${version}
