name: Delete preview environment

inputs:
  sa_key:
    description: "The service account key to use when authenticating with GCP"
    required: true
  name:
    description: "The name of the preview environment"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Deletes a preview environment
      shell: bash
      run: |
        gcloud auth activate-service-account --key-file "${PREVIEW_ENV_DEV_SA_KEY_PATH}"

        previewctl get-credentials --gcp-service-account "${PREVIEW_ENV_DEV_SA_KEY_PATH}"

        export TF_INPUT=0
        export TF_IN_AUTOMATION=true
        TF_VAR_preview_name="$(previewctl get-name --branch "${INPUT_NAME}")"
        export TF_VAR_preview_name

        leeway run dev/preview:delete-preview
